import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Morpheus",
  description: "Morpheus Privacy Policy. All data stored locally, no cloud, no tracking.",
};

export default function PrivacyPage() {
  return (
    <div className="py-24">
      <div className="prose prose-invert prose-morpheus mx-auto max-w-3xl px-6">
        <h1>Privacy Policy</h1>
        <p className="lead">Last Updated: January 2026</p>

        <h2>1. Introduction</h2>
        <p>
          This Privacy Policy describes how Morpheus (&quot;the Software&quot;) handles your data.
          Morpheus is a mobile-to-desktop AI agent control application.
        </p>
        <p>
          <strong>The short version</strong>: Morpheus stores all data locally on your devices.
          We do not collect, transmit, or store any of your data on external servers. However,
          optional features (voice mode and remote access) involve third-party services with
          their own privacy practices.
        </p>

        <h2>2. What Data Is Stored</h2>
        <p>Morpheus stores the following data locally on your devices to function:</p>
        <h3>Device and Pairing Information</h3>
        <ul>
          <li>Device names you assign to paired devices</li>
          <li>ECDH public keys for end-to-end encryption</li>
          <li>Connection URLs (local network addresses or Cloudflare tunnel URLs)</li>
          <li>Temporary pairing codes</li>
        </ul>
        <h3>Command and Session Data</h3>
        <ul>
          <li>Command history sent from mobile to desktop</li>
          <li>AI agent responses and outputs</li>
          <li>Session metadata (timestamps, identifiers, connection status)</li>
        </ul>
        <h3>User Preferences</h3>
        <ul>
          <li>Application settings (theme, voice mode, layout)</li>
          <li>Connection preferences (auto-connect, default mode)</li>
        </ul>

        <h2>3. What Is NOT Collected</h2>
        <ul>
          <li><strong>No telemetry</strong>: No usage statistics, crash reports, or behavioral analytics</li>
          <li><strong>No analytics</strong>: No third-party analytics SDKs</li>
          <li><strong>No cloud storage</strong>: No data stored on any server operated by Morpheus</li>
          <li><strong>No advertising data</strong>: No ad tracking, fingerprinting, or marketing identifiers</li>
          <li><strong>No account data</strong>: No user accounts, emails, or registration required</li>
          <li><strong>No location data</strong>: No GPS, IP geolocation, or location tracking</li>
        </ul>

        <h2>4. Local Storage</h2>
        <p>All data generated by Morpheus remains on your devices:</p>
        <ul>
          <li><strong>Desktop (macOS)</strong>: ~/Library/Application Support/Morpheus/</li>
          <li><strong>Desktop (Windows)</strong>: %APPDATA%/Morpheus/</li>
          <li><strong>Desktop (Linux)</strong>: ~/.config/Morpheus/</li>
          <li><strong>Mobile (iOS)</strong>: Keychain for keys, app container for settings</li>
          <li><strong>Mobile (Android)</strong>: Keystore for keys, app storage for settings</li>
        </ul>
        <p>
          Delete all data at any time by uninstalling the application or clearing app data
          through your device&apos;s settings.
        </p>

        <h2>5. Encryption</h2>
        <ul>
          <li><strong>Key Exchange</strong>: Elliptic Curve Diffie-Hellman (ECDH)</li>
          <li><strong>Message Encryption</strong>: TweetNaCl (compact, auditable crypto library)</li>
          <li><strong>Scope</strong>: All command and response payloads between devices</li>
          <li><strong>Key Storage</strong>: Platform-specific secure storage (Keychain, Keystore, safeStorage)</li>
        </ul>

        <h2>6. Remote Access (Cloudflare Tunnels)</h2>
        <p>When remote access is active:</p>
        <ul>
          <li>Encrypted WebSocket traffic passes through Cloudflare&apos;s infrastructure</li>
          <li>Cloudflare can see connection metadata (IPs, timestamps) but not encrypted content</li>
          <li>Tunnels are temporary and on-demand — no persistent infrastructure</li>
          <li>See <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Cloudflare&apos;s Privacy Policy</a></li>
        </ul>

        <h2>7. Voice Data</h2>
        <p>Voice mode is <strong>opt-in and disabled by default</strong>. When enabled:</p>
        <ul>
          <li>Audio is sent to the OpenAI Realtime API for processing</li>
          <li>OpenAI returns text transcriptions and voice responses</li>
          <li>No audio is stored locally by Morpheus beyond the active session</li>
          <li>See <a href="https://openai.com/privacy" target="_blank" rel="noopener noreferrer">OpenAI&apos;s Privacy Policy</a></li>
        </ul>

        <h2>8. Third-Party Services</h2>
        <ul>
          <li><strong>OpenAI</strong> — Voice mode only. Audio data shared when enabled.</li>
          <li><strong>Cloudflare</strong> — Remote access only. Encrypted traffic routed through their network.</li>
        </ul>
        <p>Neither service is contacted unless you explicitly enable the corresponding feature.</p>

        <h2>9. Data Retention</h2>
        <ul>
          <li>Local data is retained until you delete it</li>
          <li>You have full control over data retention</li>
          <li>Third-party retention: see OpenAI and Cloudflare policies</li>
        </ul>

        <h2>10. International Users (GDPR)</h2>
        <p>If you are in the EEA, UK, or Switzerland:</p>
        <ul>
          <li><strong>Lawful basis</strong>: Legitimate interest (local data) and consent (opt-in third-party features)</li>
          <li><strong>Your rights</strong>: Access, rectification, erasure, restriction, portability, objection — all exercisable directly on your device</li>
          <li><strong>Data transfers</strong>: Voice data to OpenAI (US); connection metadata via Cloudflare&apos;s global network</li>
        </ul>

        <h2>11. California Users (CCPA)</h2>
        <ul>
          <li>Morpheus does <strong>not</strong> sell personal information</li>
          <li>Delete all data by uninstalling the app</li>
          <li>No discrimination for exercising privacy rights</li>
        </ul>

        <h2>12. Children&apos;s Privacy</h2>
        <p>
          Morpheus is not designed for children under 13. We do not knowingly collect data from children.
        </p>

        <h2>13. Security</h2>
        <ul>
          <li>End-to-end encryption (ECDH + TweetNaCl)</li>
          <li>Pairing codes for secure device authentication</li>
          <li>Encrypted local storage for sensitive credentials</li>
          <li>No remote data storage eliminates server-side breach risk</li>
          <li>Minimal attack surface with local-only architecture</li>
        </ul>

        <h2>14. Changes to This Policy</h2>
        <p>
          Changes will be indicated by updating the &quot;Last Updated&quot; date. Significant changes
          will also be noted in release notes.
        </p>

        <h2>15. Contact</h2>
        <p>
          For questions about this Privacy Policy: <a href="mailto:hi@shak-tech.com">hi@shak-tech.com</a>
        </p>
        <p>
          Website: <a href="https://getmorphe.us">getmorphe.us</a>
        </p>
      </div>
    </div>
  );
}
